# Generated by Django 5.2.7 on 2025-10-08 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_foresight_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_founder',
            field=models.BooleanField(default=False),
        ),
    ]
