# Generated by Django 5.2.7 on 2025-10-26 08:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_founder'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='vote_delegate',
            field=models.ForeignKey(blank=True, help_text='Oylarını devrettiği kullanıcı. Boşsa ekip liderinin oyuyla birlikte oy kullanır.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delegated_voters', to=settings.AUTH_USER_MODEL),
        ),
    ]
