# Generated by Django 5.2.7 on 2025-10-01 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='formationvote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_votes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadervote',
            name='candidate',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_votes_received', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='leadervote',
            name='voter',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leader_votes_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='organizationformationproposal',
            name='proposed_leader',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='formation_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='formationvote',
            name='formation_proposal',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='organization.organizationformationproposal'),
        ),
        migrations.AddField(
            model_name='provinceorganization',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_province_org', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='squad',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_squad', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_team', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='team',
            name='parent_squad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teams', to='organization.squad'),
        ),
        migrations.AddField(
            model_name='union',
            name='leader',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_union', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='union',
            name='parent_province_org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='unions', to='organization.provinceorganization'),
        ),
        migrations.AddField(
            model_name='squad',
            name='parent_union',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='squads', to='organization.union'),
        ),
        migrations.AlterUniqueTogether(
            name='leadervote',
            unique_together={('voter', 'voter_level')},
        ),
        migrations.AlterUniqueTogether(
            name='formationvote',
            unique_together={('formation_proposal', 'voter')},
        ),
    ]
