# Generated by Django 5.2.7 on 2025-10-03 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='leadervote',
            name='voter_level',
            field=models.CharField(choices=[('TEAM', 'Ekip Lideri'), ('SQUAD', 'Takım Lideri'), ('UNION', 'Birlik Lideri'), ('PROVINCE_ORG', 'İl Örgütü Lideri')], max_length=20),
        ),
    ]
