# Generated by Django 5.2.7 on 2025-10-17 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0003_alter_leadervote_voter_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaderRemovalVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.CharField(choices=[('TEAM', 'Ekip'), ('SQUAD', 'Takım'), ('UNION', 'Birlik')], max_length=20)),
                ('entity_id', models.IntegerField()),
                ('reason', models.TextField(help_text='Atma gerekçesi')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('PASSED', 'Kabul Edildi'), ('REJECTED', 'Reddedildi')], default='ACTIVE', max_length=10)),
                ('yes_votes', models.IntegerField(default=0)),
                ('no_votes', models.IntegerField(default=0)),
                ('current_leader', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_votes_against', to=settings.AUTH_USER_MODEL)),
                ('initiated_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='removal_votes_initiated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='RemovalVoteCast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote', models.CharField(choices=[('YES', 'Evet - Atılsın'), ('NO', 'Hayır - Kalmalı')], max_length=3)),
                ('voted_at', models.DateTimeField(auto_now_add=True)),
                ('removal_vote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='organization.leaderremovalvote')),
                ('voter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('removal_vote', 'voter')},
            },
        ),
    ]
