# Generated by Django 5.2.7 on 2025-10-01 23:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchivedProposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('archived_discussions', models.JSONField()),
                ('final_vote_result', models.JSONField()),
                ('archived_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='DoctrineArticle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_number', models.IntegerField()),
                ('article_type', models.CharField(choices=[('FOUNDATION_LAW', 'Kuruluş Yasası'), ('NORMAL_LAW', 'Normal Yasa')], max_length=20)),
                ('content', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('last_modified_date', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['article_type', 'article_number'],
            },
        ),
        migrations.CreateModel(
            name='Proposal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('ADD', 'Madde Ekleme'), ('MODIFY', 'Madde Değişikliği'), ('FOUNDER_REVISION', 'Kurucu Genel Düzenleme'), ('NAME_CHANGE', 'İsim Değişikliği')], max_length=20)),
                ('proposed_content', models.TextField()),
                ('proposed_by_level', models.CharField(choices=[('SQUAD', 'Takım'), ('UNION', 'Birlik'), ('PROVINCE_ORG', 'İl Örgütü'), ('FOUNDER', 'Kurucu')], max_length=20)),
                ('proposed_by_entity_id', models.IntegerField()),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('status', models.CharField(choices=[('ACTIVE', 'Aktif'), ('PASSED', 'Kabul Edildi'), ('REJECTED', 'Reddedildi'), ('ARCHIVED', 'Arşivlendi')], default='ACTIVE', max_length=10)),
                ('vote_yes_count', models.IntegerField(default=0)),
                ('vote_abstain_count', models.IntegerField(default=0)),
                ('vote_veto_count', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_choice', models.CharField(choices=[('YES', 'Kabul'), ('ABSTAIN', 'Çekimser'), ('VETO', 'Veto')], max_length=10)),
                ('voted_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Discussion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='doctrine.discussion')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
    ]
