# Generated by Django 5.2.7 on 2025-10-03 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vote',
            name='last_changed_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
