# Generated by Django 5.2.7 on 2025-10-03 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0004_alter_discussion_options_discussion_downvotes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='discussion',
            name='article',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discussions', to='doctrine.doctrinearticle'),
        ),
    ]
