# Generated by Django 5.2.7 on 2025-10-03 21:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0005_alter_discussion_article'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProposalDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('proposal_type', models.CharField(choices=[('NEW_ARTICLE', 'Yeni Madde'), ('AMEND_ARTICLE', 'Madde Değişikliği'), ('REPEAL_ARTICLE', 'Madde İptali'), ('RENAME_ARTICLE', 'İsim Değişikliği')], max_length=20)),
                ('proposed_content', models.TextField()),
                ('draft_title', models.CharField(blank=True, max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('related_article', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doctrine.doctrinearticle')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_drafts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
    ]
