# Generated by Django 5.2.7 on 2025-10-03 21:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0006_proposaldraft'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('proposal_created', 'Öneri Oluşturuldu'), ('proposal_passed', 'Öneri Kabul Edildi'), ('proposal_rejected', 'Öneri Reddedildi'), ('comment_added', 'Yorum Eklendi'), ('vote_cast', 'Oy Kullanıldı'), ('leader_changed', 'Lider Değişti'), ('organization_formed', 'Organizasyon Oluşturuldu'), ('team_created', 'Ekip Oluşturuldu')], max_length=30)),
                ('description', models.TextField()),
                ('related_url', models.CharField(blank=True, max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
