# Generated by Django 5.2.7 on 2025-10-04 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0007_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_type',
            field=models.CharField(choices=[('proposal_created', 'Öneri Oluşturuldu'), ('proposal_passed', 'Öneri Kabul Edildi'), ('proposal_rejected', 'Öneri Reddedildi'), ('comment_added', 'Yorum Eklendi'), ('vote_cast', 'Oy Kullanıldı'), ('leader_changed', 'Lider Değişti'), ('organization_formed', 'Organizasyon Oluşturuldu'), ('team_created', 'Ekip Oluşturuldu'), ('prediction_created', 'Tahmin Oluşturuldu'), ('prediction_expired', 'Tahmin Süresi Doldu'), ('prediction_verified', 'Tahmin Doğrulandı')], max_length=30),
        ),
    ]
