# Generated by Django 5.2.7 on 2025-10-08 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0008_alter_activity_activity_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctrinearticle',
            name='justification',
            field=models.TextField(blank=True, help_text='Gerekçelendirme (sadece kuruluş ilkeleri için)', null=True),
        ),
    ]
