# Generated by Django 5.2.7 on 2025-10-08 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0009_doctrinearticle_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='justification',
            field=models.TextField(blank=True, help_text='Önerinin gerekçesi', null=True),
        ),
    ]
