# Generated by Django 5.2.7 on 2025-10-09 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0010_proposal_justification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinearticle',
            name='article_type',
            field=models.CharField(choices=[('FOUNDATION_LAW', 'İlke'), ('NORMAL_LAW', 'Yasa')], max_length=20),
        ),
    ]
