# Generated by Django 5.2.7 on 2025-10-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0011_alter_doctrinearticle_article_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctrinearticle',
            name='justification',
            field=models.TextField(blank=True, help_text='Gerekçelendirme', null=True),
        ),
    ]
