# Generated by Django 5.2.7 on 2025-10-10 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0012_alter_doctrinearticle_justification'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='original_article_content',
            field=models.TextField(blank=True, help_text='Değişiklik önerisi için: Maddenin değişiklikten önceki hali', null=True),
        ),
    ]
