# Generated by Django 5.2.7 on 2025-10-10 07:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0014_alter_activity_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version_number', models.IntegerField(help_text='Versiyon numarası (1, 2, 3...)')),
                ('content', models.TextField(help_text='Bu versiyondaki madde içeriği')),
                ('justification', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='doctrine.doctrinearticle')),
                ('changed_by_proposal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='article_versions', to='doctrine.proposal')),
            ],
            options={
                'ordering': ['-version_number'],
                'unique_together': {('article', 'version_number')},
            },
        ),
    ]
