# Generated by Django 5.2.7 on 2025-10-10 07:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0015_articleversion'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArticleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('slug', models.SlugField(unique=True)),
                ('color', models.CharField(default='#3B82F6', help_text='Hex renk kodu (örn: #3B82F6)', max_length=7)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='doctrinearticle',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='articles', to='doctrine.articletag'),
        ),
    ]
