# Generated by Django 5.2.7 on 2025-10-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0016_articletag_doctrinearticle_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposed_tags',
            field=models.TextField(blank=True, help_text="Önerilen etiketler (virgülle ayrılmış ID'ler)", null=True),
        ),
    ]
