# Generated by Django 5.2.7 on 2025-10-10 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0017_proposal_proposed_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposaldraft',
            name='justification',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='proposaldraft',
            name='proposed_tags',
            field=models.TextField(blank=True, help_text="Önerilen etiketler (virgülle ayrılmış ID'ler)"),
        ),
        migrations.AlterField(
            model_name='proposal',
            name='proposal_type',
            field=models.CharField(choices=[('ADD', 'Madde Ekleme'), ('MODIFY', 'Madde Değişikliği'), ('REMOVE', 'Madde Kaldırma'), ('FOUNDER_REVISION', 'Kurucu Genel Düzenleme'), ('NAME_CHANGE', 'İsim Değişikliği')], max_length=20),
        ),
        migrations.AlterField(
            model_name='proposaldraft',
            name='proposed_content',
            field=models.TextField(blank=True),
        ),
    ]
