# Generated by Django 5.2.7 on 2025-10-11 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0018_proposaldraft_justification_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference_type', models.CharField(choices=[('BOOK', 'Kitap'), ('ARTICLE', 'Makale'), ('JOURNAL', 'Dergi'), ('WEBSITE', 'Web Sitesi'), ('REPORT', 'Rapor'), ('THESIS', 'Tez'), ('OTHER', 'Diğer')], default='BOOK', max_length=20)),
                ('author', models.CharField(help_text='Yazar(lar) - Örn: Kant, Immanuel veya Smith, J. & Doe, A.', max_length=500)),
                ('title', models.CharField(help_text='Eser başlığı', max_length=500)),
                ('year', models.IntegerField(help_text='Yayın yılı')),
                ('publisher', models.CharField(blank=True, help_text='Yayınevi', max_length=300)),
                ('city', models.CharField(blank=True, help_text='Yayın yeri', max_length=100)),
                ('url', models.URLField(blank=True, help_text='Online kaynak linki')),
                ('doi', models.CharField(blank=True, help_text='DOI numarası', max_length=100)),
                ('isbn', models.CharField(blank=True, help_text='ISBN numarası', max_length=50)),
                ('pages', models.CharField(blank=True, help_text='Sayfa aralığı - Örn: 157-189', max_length=50)),
                ('notes', models.TextField(blank=True, help_text='Notlar, açıklamalar')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_verified', models.BooleanField(default=False, help_text='Kaynağın doğruluğu onaylandı mı?')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Referans',
                'verbose_name_plural': 'Referanslar',
                'ordering': ['author', 'year'],
            },
        ),
        migrations.CreateModel(
            name='ProposalReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.CharField(blank=True, help_text='Atıfta kullanılan sayfa numarası - Örn: s.157', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('proposal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='doctrine.proposal')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proposal_usages', to='doctrine.reference')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('proposal', 'reference')},
            },
        ),
        migrations.CreateModel(
            name='ArticleReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page_number', models.CharField(blank=True, help_text='Atıfta kullanılan sayfa numarası', max_length=50)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references', to='doctrine.doctrinearticle')),
                ('reference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='article_usages', to='doctrine.reference')),
            ],
            options={
                'ordering': ['added_at'],
                'unique_together': {('article', 'reference')},
            },
        ),
    ]
