# Generated by Django 5.2.7 on 2025-10-11 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0019_reference_proposalreference_articlereference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proposal',
            name='proposed_by_level',
            field=models.CharField(choices=[('TEAM', 'Ekip'), ('SQUAD', 'Takım'), ('UNION', 'Birlik'), ('PROVINCE_ORG', 'İl Örgütü'), ('FOUNDER', 'Kurucu')], max_length=20),
        ),
    ]
