# Generated by Django 5.2.7 on 2025-10-19 00:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0020_alter_proposal_proposed_by_level'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='created_by',
            field=models.ForeignKey(help_text='Öneriyi oluşturan kullanıcı', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_proposals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='doctrinearticle',
            name='article_type',
            field=models.CharField(choices=[('FOUNDATION_LAW', '🏛️ İlke'), ('NORMAL_LAW', 'Yasa')], max_length=20),
        ),
    ]
