# Generated by Django 5.2.7 on 2025-10-26 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('doctrine', '0021_proposal_created_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proposal',
            name='proposed_article_type',
            field=models.CharField(choices=[('FOUNDATION_LAW', 'İlke'), ('NORMAL_LAW', 'Program')], default='NORMAL_LAW', help_text='Yeni madde eklenirken: İlke mi Program maddesi mi?', max_length=20),
        ),
    ]
