# Generated by Django 5.2.7 on 2025-10-01 23:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('target_level', models.CharField(choices=[('TEAM', 'Ekip'), ('SQUAD', 'Takım'), ('UNION', 'Birlik'), ('PROVINCE_ORG', 'İl Örgütü'), ('ALL', 'Tüm Üyeler')], max_length=20)),
                ('target_entity_id', models.IntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('NEW_VOTE', 'Yeni Oylama'), ('ANNOUNCEMENT', 'Duyuru'), ('LEADER_CHANGE', 'Lider Değişikliği'), ('FORMATION_PROPOSAL', 'Örgüt Oluşturma Önerisi'), ('VOTE_RESULT', 'Oylama Sonucu')], max_length=20)),
                ('message', models.TextField()),
                ('related_object_id', models.IntegerField(blank=True, null=True)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
