# Generated by Django 5.2.7 on 2025-10-09 13:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_alter_notification_notification_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_PROPOSAL', 'Yeni Öneri'), ('PROPOSAL_PASSED', 'Öneri Kabul Edildi'), ('PROPOSAL_REJECTED', 'Öneri Reddedildi'), ('COMMENT_REPLY', 'Yoruma Yanıt'), ('LEADER_CHANGE', 'Lider Değişikliği'), ('FORMATION_PROPOSAL', 'Örgüt Oluşturma Önerisi'), ('FORMATION_APPROVED', 'Örgüt Oluşturuldu'), ('ANNOUNCEMENT', 'Duyuru'), ('MENTION', 'Bahsedildin'), ('NEW_MESSAGE', 'Yeni Mesaj')], max_length=20),
        ),
        migrations.CreateModel(
            name='LeaderMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_messages', to=settings.AUTH_USER_MODEL)),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
