# Generated by Django 5.2.7 on 2025-10-09 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_alter_notification_notification_type_leadermessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('NEW_PROPOSAL', 'Yeni Öneri'), ('PROPOSAL_PASSED', 'Öneri Kabul Edildi'), ('PROPOSAL_REJECTED', 'Öneri Reddedildi'), ('COMMENT_REPLY', 'Yoruma Yanıt'), ('LEADER_CHANGE', 'Lider Değişikliği'), ('FORMATION_PROPOSAL', 'Örgüt Oluşturma Önerisi'), ('FORMATION_APPROVED', 'Örgüt Oluşturuldu'), ('ANNOUNCEMENT', 'Duyuru'), ('MENTION', 'Bahsedildin')], max_length=20),
        ),
    ]
